### ISSUE TITLE
Unable to pass APIRouter when registering routes using add_routes.

### ISSUE THREAD

**Issue by hikilyc** [langchain-ai/langserve#129]
```python
app = FastAPI()

router = APIRouter()

add_routes(
    router,
    ChatOpenAI(),
    path="/chat",
)

app.include_router(router)
```

produces the following error:

```
Traceback (most recent call last):
  File "...\app\main.py", line 21, in <module>
    add_routes(
  File "...\.venv\lib\site-packages\langserve\server.py", line 300, in add_routes
    _register_path_for_app(app, path)
  File "...\.venv\lib\site-packages\langserve\server.py", line 232, in _register_path_for_app
    if app in _APP_TO_PATHS:
  File "...\pyenv\pyenv-win\versions\3.10.6\lib\weakref.py", line 460, in __contains__
    return wr in self.data
TypeError: unhashable type: 'APIRouter'
```

**Comment by eyurtsev** [comment]
thanks for reporting!

**Comment by eyurtsev** [comment]
Fixed will be available in next release
