### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'langserve.packages'

### ISSUE THREAD

**Issue by xiechengmude** [langchain-ai/langserve#190]
Traceback (most recent call last):
  File "/root/miniconda3/envs/langserve/bin/langchain", line 5, in <module>
    from langchain_cli.cli import app
  File "/root/miniconda3/envs/langserve/lib/python3.11/site-packages/langchain_cli/cli.py", line 6, in <module>
    from langchain_cli.namespaces import app as app_namespace
  File "/root/miniconda3/envs/langserve/lib/python3.11/site-packages/langchain_cli/namespaces/app.py", line 11, in <module>
    from langserve.packages import get_langserve_export
ModuleNotFoundError: No module named 'langserve.packages'

Env: Python3.11 Conda, langchain langchain-cli 0.0.15 Langserve

**Comment by edeng23** [comment]
Same here

**Comment by efriis** [comment]
It's out in langchain-cli 0.0.16! This will work with `pip install -U langchain-cli langserve`

langserve >= 0.0.24 is only compatible with langchain-cli >= 0.0.16
