### ISSUE TITLE
langchain commands are not working 

### ISSUE THREAD

**Issue by payalcha** [langchain-ai/langserve#254]
cmd >>  langchain version
Traceback (most recent call last):
  File "/var/github/workspace/langchain-serve/app/bin/langchain", line 5, in <module>
    from langchain_cli.cli import app
  File "/var/github/workspace/langchain-serve/app/lib/python3.8/site-packages/langchain_cli/cli.py", line 6, in <module>
    from langchain_cli.namespaces import app as app_namespace
  File "/var/github/workspace/langchain-serve/app/lib/python3.8/site-packages/langchain_cli/namespaces/app.py", line 26, in <module>
    from langchain_cli.utils.pyproject import (
  File "/var/github/workspace/langchain-serve/app/lib/python3.8/site-packages/langchain_cli/utils/pyproject.py", line 15, in <module>
    pyproject_toml: Path, local_editable_dependencies: Iterable[tuple[str, Path]]
TypeError: 'type' object is not subscriptable

**Comment by efriis** [comment]
Hey @payalcha ! Could you try upgrading your langchain-cli version with `pip install -U langchain-cli`?

**Comment by ChengyangDu** [comment]
Same issuse. Have tried to `pip install -U langchain-cli ` but not work. Versions are listed below
```
langchain                                0.0.343
langchain-cli                            0.0.19
langchain-core                           0.0.7 
```

**Comment by efriis** [comment]
Oh oops - could you try `langchain --version`?

Is there somewhere that you saw `langchain version` was a valid command?
