### ISSUE TITLE
Streaming from Langserve fails on Vercel (serverless) deployments

### ISSUE THREAD

**Issue by znat** [langchain-ai/langserve#315]
Hi,

I'm having errors when streaming from a langserve server deployed on Vercel. I have a simple reproducible example:

```python
#server.py

"""Example LangChain server exposes multiple runnables (LLMs in this case)."""

from fastapi import FastAPI
from langchain.chat_models import ChatOpenAI

from langserve import add_routes

app = FastAPI(
    title="LangChain Server",
    version="1.0",
    description="Spin up a simple api server using Langchain's Runnable interfaces",
)

add_routes(
    app,
    ChatOpenAI(),
    path="/openai",
)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="localhost", port=8000)

```

pyproject.toml
```toml
[tool.poetry.dependencies]
python = "3.9.18"
openai = "^1.2.0"
tiktoken = "^0.5.1"
jinja2 = "^3.1.2"
aiofiles = "^23.2.1"
psycopg2-binary = "^2.9.9"
pgvector = "^0.2.4"
fastapi = "^0.104.1"
langchain = "^0.0.349"
langserve = "^0.0.35"
sse-starlette = "^1.8.2"
```

vercel.json:

```json
{
    "public": false,
    "builds": [
        {
            "src": "redrock/server.py",
            "use": "@vercel/python"
        }
    ],
    "routes": [
        {
            "src": "/(.*)",
            "dest": "/redrock/server.py"
        }
    ]
}
```

Deployment on Vercel works fine, `/invoke` calls work fine. However `stream` and `stream_log` endpoints don't. 
To be precise they work once and then fail with the following error:

```
[ERROR] RuntimeError: Task <Task pending name='sse_starlette.sse.EventSourceResponse.__call__.<locals>.wrap' coro=<EventSourceResponse.__call__.<locals>.wrap() running at /var/task/sse_starlette/sse.py:258> cb=[TaskGroup._spawn.<locals>.task_done() at /var/task/anyio/_backends/_asyncio.py:661]> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/var/task/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/var/task/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/var/task/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/var/task/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/var/task/sse_starlette/sse.py", line 235, in listen_for_exit_signal
    await AppStatus.should_exit_event.wait()
  File "/var/task/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
  File "/var/lang/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
```

**Comment by eyurtsev** [comment]
https://vercel.com/docs/functions/streaming#choosing-a-runtime

---

Could you check what happens when you use edge functions?

You could also try to stream the code below which starts to stream immediately without delays:

```python
from langchain.schema.runnable import Runnable

class CustomStream(Runnable):
    def invoke(*args, **kwargs):
        raise NotImplementedError()
        
    def stream(*args, **kwargs):
        yield from 'hello'

for chunk in CustomStream().stream('h'):
    print(chunk)
```

**Comment by eyurtsev** [comment]
I'm going to close this as this does not seem to be a langserve issue, but a deployment issue.

**Comment by zer0Tokens** [comment]
Hey, did you figure out why the error happened? I am having the same issue

**Comment by vadimshvetsov** [comment]
Also have the same issue. For me streaming works on the first request but then I always receive 500 until redeploy.
