### ISSUE TITLE
TypeError: Type is not JSON serializable: ModelMetaclass

### ISSUE THREAD

**Issue by 1100111GTH** [langchain-ai/langserve#471]
```
INFO:     123.185.63.166:0 - "POST /base_answer/invoke HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
RuntimeError: super(): __class__ cell not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/server.py", line 464, in invoke
    return await api_handler.invoke(request)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/api_handler.py", line 720, in invoke
    output=self._serializer.dumpd(output),
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/serialization.py", line 164, in dumpd
    return orjson.loads(orjson.dumps(obj, default=default))
TypeError: Type is not JSON serializable: ModelMetaclass
```

is anyone knows how to fix this?

**Comment by Jose-cd** [comment]
did you find the solution?
