### ISSUE TITLE
TypeError: Type is not JSON serializable: numpy.float64

### ISSUE THREAD

**Issue by mieslep** [langchain-ai/langserve#551]
I've narrowed down the problem to one that reproduces on the `weblangchain` repo https://github.com/langchain-ai/weblangchain 

I'm trying to update to the latest versions of Langchain/Langsmith/LangchainJS/etc (including to the new "community" approach). I have reproduced on this (forked) branch https://github.com/mieslep/weblangchain/tree/compoent_and_update 

The chain seems to run correctly https://smith.langchain.com/public/296c9325-2dce-4f2c-a533-64baac6c50fc/r 

But it seems that somehow in the handling of the response back to the client something is getting mangled? (Not sure why the embedding vector might be returned back to the client...)

```
INFO:     127.0.0.1:62681 - "POST /chat/stream_log HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
RuntimeError: super(): __class__ cell not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\phil\git\weblangchain\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.....
  File "C:\Users\phil\git\weblangchain\.venv\Lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "C:\Users\phil\git\weblangchain\.venv\Lib\site-packages\langserve\api_handler.py", line 1106, in _stream_log
    "data": self._serializer.dumps(data).decode("utf-8"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phil\git\weblangchain\.venv\Lib\site-packages\langserve\serialization.py", line 168, in dumps
    return orjson.dumps(obj, default=default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: numpy.float64
```

**Comment by mieslep** [comment]
fwiw, it fails in /chat/playground/ as well.

**Comment by eyurtsev** [comment]
numpy.float64 is not json serializable -- you need to convert it into a json format so that it can be transmitted over the wire to the front end.
